---
title: "Prediction Assignment"
author: "Carlos Araya"
date: "17 de abril de 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data

1. Load the data.

```{r}
library(caret)
pml_training <- read.csv("~/PML_Assignment/pml-training.csv", na.strings = c("", "NA", "#DIV/0!"))
pml_testing <- read.csv("~/PML_Assignment/pml-testing.csv", na.strings = c("", "NA", "#DIV/0!"))

# define train and test for cross validation
inTrain <- createDataPartition(y=pml_training$classe,
                                p=0.75,list=FALSE)
training_0 <- pml_training[inTrain,]
testing_0 <- pml_training[-inTrain,]

# We count NAs
NAs <- apply(training_0, 2, function(x) {
    sum(is.na(x))
})
#(NAs)
training <- training_0[, which(NAs == 0)]
testing <- testing_0[, which(NAs == 0)]
pml_test <- pml_testing[, which(NAs == 0)]
```

2. Modeling

```{r}
modelFit <- train(classe ~ ., data = training, method = "rf"
                  ,trControl=trainControl(method = "cv", number = 4))
modelFit
predictions <- predict(modelFit, newdata = testing)
confusionMatrix(predictions, testing$classe)
```

3. Forecast
```{r}
predictions_2 <- predict(modelFit, newdata = pml_test)
predictions_2
```